# Generated by Django 2.2.4 on 2019-08-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='lasttName',
            new_name='lastName',
        ),
    ]
